---
- name: Download Artifacts
  shell:  |
    curl -H "Circle-Token: $CI_TOKEN" https://circleci.com/api/v1.1/project/github/jafman/udacity-nd-project3/latest/artifacts \
    | grep -o 'https://[^"]*' \
    | wget --verbose --header "Circle-Token: $CIRCLE_TOKEN" --input-file -
    ls
    tar -xvzf artifact.tar.gz

- name: Install Dependencies and Start App
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
